version: "3.8"

services:
  backend:
    image: registry.vgscq.cc/vgscq/hwinfo-db:backend
    restart: unless-stopped
    volumes:
      - /docker/hwdb/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Prague
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hwdb-backend.rule=Host(`hwdb.vgscq.cc`) && (Path(`/update_notes`) || Path(`/submit`) || Path(`/pcs`) || Path(`/pc`) || PathPrefix(`/pc/`))"
      - "traefik.http.routers.hwdb-backend.priority=20"
      - "traefik.http.routers.hwdb-backend.entrypoints=https"
      - "traefik.http.routers.hwdb-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.hwdb-backend.loadbalancer.server.port=5000"
    command: python -u /app/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - traefik
      - hwdb

  frontend:
    image: registry.vgscq.cc/vgscq/hwinfo-db:frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Prague
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hwdb-frontend.rule=Host(`hwdb.vgscq.cc`) && (PathPrefix(`/`) && !Path(`/update_notes`) && !Path(`/submit`) && !Path(`/pcs`) && !Path(`/pc`) && !PathPrefix(`/pc/`))"
      - "traefik.http.routers.hwdb-frontend.priority=10"
      - "traefik.http.routers.hwdb-frontend.entrypoints=https"
      - "traefik.http.routers.hwdb-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.hwdb-frontend.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - traefik
      - hwdb

networks:
  traefik:
    external: true
  hwdb:
    external: false
